steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flask-app']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'flask-app', '--image', 'gcr.io/$PROJECT_ID/flask-app', '--region','asia-southeast1', '--platform', 'managed']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images:
- 'gcr.io/$PROJECT_ID/flask-app'
